name: api_bk
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  json_annotation: ^4.8.1
  orm: ^3.4.5

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
